# Generated by Django 5.1.6 on 2025-03-01 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetrics',
            fields=[
                ('metric_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('GROWTH', '成长型'), ('LEVEL', '水平型')], max_length=10)),
                ('weight', models.FloatField()),
                ('formula', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('grade_name', models.CharField(max_length=50)),
                ('grade_level', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=9)),
                ('term', models.CharField(choices=[('1', '第一学期'), ('2', '第二学期')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_type', models.CharField(choices=[('MAIN', '主课'), ('MINOR', '副课')], max_length=10)),
                ('description', models.TextField()),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MIDTERM', '期中考试'), ('FINAL', '期末考试'), ('ENTRANCE', '入学考试')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_score', models.FloatField()),
                ('status', models.CharField(default='PLANNED', max_length=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=10)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('income_level', models.CharField(choices=[('LOW', '低收入'), ('MIDDLE', '中等收入'), ('HIGH', '高收入')], max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('school_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
                ('school_type', models.CharField(choices=[('PRIMARY', '小学'), ('JUNIOR', '初中'), ('HIGH', '高中')], max_length=10)),
                ('school_nature', models.CharField(choices=[('PUBLIC', '公立'), ('PRIVATE', '私立')], max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('principal', models.CharField(max_length=50)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class')),
                ('current_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grade')),
                ('current_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.family')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectRelation',
            fields=[
                ('relation_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(choices=[('PREREQUISITE', '先修课程'), ('RELATED', '相关课程')], max_length=15)),
                ('description', models.TextField()),
                ('subject1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='core.subject')),
                ('subject2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_to', to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(choices=[('JUNIOR', '初级'), ('MIDDLE', '中级'), ('SENIOR', '高级')], max_length=10)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('current_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('raw_score', models.FloatField()),
                ('standard_score', models.FloatField()),
                ('percentile', models.FloatField()),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], max_length=1)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherTeam',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_teams', to='core.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ValueAddedEvaluation',
            fields=[
                ('eval_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('SCHOOL', '学校'), ('TEACHER', '教师'), ('STUDENT', '学生')], max_length=10)),
                ('target_id', models.CharField(max_length=10)),
                ('base_score', models.FloatField()),
                ('current_score', models.FloatField()),
                ('added_value', models.FloatField()),
                ('factors', models.JSONField(default=dict)),
                ('status', models.CharField(default='DRAFT', max_length=10)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
            ],
        ),
    ]
