# Generated by Django 5.1.6 on 2025-03-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': '班级', 'verbose_name_plural': '班级管理'},
        ),
        migrations.AlterModelOptions(
            name='evaluationmetrics',
            options={'verbose_name': '评价指标', 'verbose_name_plural': '评价指标管理'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': '考试', 'verbose_name_plural': '考试管理'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': '家庭', 'verbose_name_plural': '家庭管理'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name': '年级', 'verbose_name_plural': '年级管理'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': '区域', 'verbose_name_plural': '区域管理'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '学校', 'verbose_name_plural': '学校管理'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'verbose_name': '成绩', 'verbose_name_plural': '成绩管理'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': '学期', 'verbose_name_plural': '学期管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生管理'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': '学科', 'verbose_name_plural': '学科管理'},
        ),
        migrations.AlterModelOptions(
            name='subjectrelation',
            options={'verbose_name': '学科关联', 'verbose_name_plural': '学科关联管理'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师管理'},
        ),
        migrations.AlterModelOptions(
            name='teacherteam',
            options={'verbose_name': '教师团队', 'verbose_name_plural': '教师团队管理'},
        ),
        migrations.AlterModelOptions(
            name='valueaddedevaluation',
            options={'verbose_name': '增值评价', 'verbose_name_plural': '增值评价管理'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='admin_position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cert_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='entry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='graduate_school',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_number',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_class_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='main_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='major',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='secondary_subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teaching_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
