# Generated by Django 5.1.6 on 2025-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_exam_number_student_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
