# Generated by Django 5.1.6 on 2025-03-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_semester_semester_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
