# Generated by Django 5.1.6 on 2025-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_valueaddedevaluation_eval_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationmetrics',
            name='metric_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subjectrelation',
            name='relation_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
