# Generated by Django 5.1.6 on 2025-03-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_evaluationmetrics_metric_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='father_name',
            new_name='family_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='father_phone',
        ),
        migrations.RemoveField(
            model_name='family',
            name='income_level',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='mother_phone',
        ),
        migrations.RemoveField(
            model_name='family',
            name='region',
        ),
        migrations.AddField(
            model_name='family',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
