# Generated by Django 5.1.6 on 2025-03-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_father_name_family_family_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubjectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teachers', to='core.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='core.teacher')),
            ],
            options={
                'verbose_name': '教师学科班级关联',
                'verbose_name_plural': '教师学科班级关联管理',
                'indexes': [models.Index(fields=['school', 'semester'], name='core_teache_school__02963d_idx')],
                'unique_together': {('teacher', 'subject', 'class_obj', 'semester')},
            },
        ),
    ]
