# Generated by Django 5.1.6 on 2025-03-03 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studenthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherHistory',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_class_teacher', models.BooleanField(default=False, verbose_name='是否班主任')),
                ('admin_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='行政职务')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('ACTIVE', '在任'), ('COMPLETED', '已结束'), ('SUSPENDED', '暂停')], default='ACTIVE', max_length=20)),
                ('class_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.class')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.teacher')),
            ],
            options={
                'verbose_name': '教师历史记录',
                'verbose_name_plural': '教师历史记录',
                'unique_together': {('teacher', 'school', 'semester', 'subject', 'class_field')},
            },
        ),
    ]
