# Generated by Django 5.1.6 on 2025-03-04 00:36

import django.db.models.deletion
from django.db import migrations, models

def forward_func(apps, schema_editor):
    Score = apps.get_model('core', 'Score')
    Exam = apps.get_model('core', 'Exam')
    # 更新每个成绩记录的semester_id
    updated = 0
    for score in Score.objects.all():
        if not score.semester_id and hasattr(score, 'exam') and score.exam_id:
            try:
                exam = Exam.objects.get(pk=score.exam_id)
                score.semester_id = exam.semester_id
                score.save(update_fields=['semester_id'])
                updated += 1
            except Exam.DoesNotExist:
                pass  # 若考试不存在，则跳过
    
    print(f"Updated {updated} score records with semester_id")

def reverse_func(apps, schema_editor):
    # 不需要回滚操作
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_teacherhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade', 'class_name', 'semester')},
        ),
        migrations.RunPython(forward_func, reverse_func),
    ]
