# Generated by Django 5.1.6 on 2025-03-04 05:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_class_semester_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='semester_id',
            field=models.CharField(db_index=True, default=core.models.get_default_semester, max_length=20),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['semester_id'], name='core_score_semeste_104bf4_idx'),
        ),
    ]
