# Generated by Django 5.1.7 on 2025-03-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_score_semester_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
