# Generated by Django 5.1.7 on 2025-03-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_score_score_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='admin_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
