# Generated by Django 5.1.7 on 2025-03-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_teacher_admin_position_alter_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.CharField(help_text='班级唯一标识', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='main_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='secondary_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'exam', 'subject'), name='unique_score_record'),
        ),
    ]
