# Generated by Django 5.1.7 on 2025-03-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_class_class_id_alter_teacher_main_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValueAddedConfig',
            fields=[
                ('config_id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('config_name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('SCHOOL', '学校'), ('TEACHER', '教师'), ('STUDENT', '学生')], max_length=10)),
                ('method', models.CharField(choices=[('simple_difference', '简单差值法'), ('simple_difference_tes', 'TES差值法'), ('predicted_difference', '预测差值法'), ('hlm', '多层线性模型'), ('ml_random_forest', '随机森林'), ('ml_neural_network', '神经网络')], max_length=25)),
                ('parameters', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
            options={
                'verbose_name': '增值评价配置',
                'verbose_name_plural': '增值评价配置管理',
            },
        ),
    ]
