# Generated by Django 5.1.7 on 2025-05-05 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_valueaddedconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('config', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('charts_data', models.JSONField(default=dict)),
                ('file_paths', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='teachersubjectclass',
            options={},
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='class_obj',
            field=models.ForeignKey(blank=True, db_column='class_obj_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school'),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
        migrations.AlterField(
            model_name='teachersubjectclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher'),
        ),
        migrations.AlterField(
            model_name='valueaddedconfig',
            name='method',
            field=models.CharField(choices=[('simple_difference', '简单差值法'), ('simple_difference_tes', 'TES差值法'), ('predicted_difference', '预测差值法'), ('hlm', '多层线性模型'), ('ml_random_forest', '随机森林'), ('ml_neural_network', '神经网络')], max_length=60),
        ),
    ]
