# Generated by Django 5.1.7 on 2025-05-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_teachersubjectclass_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student_id', 'exam_id'], name='core_score_student_2da113_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student_id', 'exam_id', 'subject_id'], name='core_score_student_dbf93e_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['exam_id', 'subject_id'], name='core_score_exam_id_c080db_idx'),
        ),
    ]
