# Generated by Django 5.1.7 on 2025-05-08 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_fix_teachersubjectclass_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('params', models.JSONField(default=dict)),
                ('results_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DistrictExamFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(default='TOTAL', max_length=20, verbose_name='科目ID')),
                ('avg_score', models.FloatField(verbose_name='平均分')),
                ('avg_standard_score', models.FloatField(default=0, verbose_name='标准分均值')),
                ('std_dev', models.FloatField(verbose_name='标准差')),
                ('total_students', models.IntegerField(verbose_name='学生总数')),
                ('max_score', models.FloatField(verbose_name='最高分')),
                ('min_score', models.FloatField(verbose_name='最低分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='关联考试')),
            ],
            options={
                'verbose_name': '区域考试特征',
                'verbose_name_plural': '区域考试特征管理',
                'unique_together': {('exam', 'subject_id')},
            },
        ),
        migrations.CreateModel(
            name='SchoolExamFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(default='TOTAL', max_length=20, verbose_name='科目ID')),
                ('avg_score', models.FloatField(verbose_name='校平均分')),
                ('avg_standard_score', models.FloatField(default=0, verbose_name='标准分均值')),
                ('std_dev', models.FloatField(verbose_name='校标准差')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('percentile', models.FloatField(verbose_name='百分位')),
                ('student_count', models.IntegerField(verbose_name='学生数')),
                ('grade_count', models.IntegerField(default=1, verbose_name='年级数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('district_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_insights.districtexamfeature', verbose_name='区级特征')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='关联考试')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school', verbose_name='关联学校')),
            ],
            options={
                'verbose_name': '校级考试特征',
                'verbose_name_plural': '校级考试特征管理',
            },
        ),
        migrations.CreateModel(
            name='ClassExamFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.CharField(default='TOTAL', max_length=20, verbose_name='科目ID')),
                ('avg_score', models.FloatField(verbose_name='班级平均分')),
                ('std_dev', models.FloatField(verbose_name='班级标准差')),
                ('school_rank', models.IntegerField(verbose_name='校内排名')),
                ('school_percentile', models.FloatField(verbose_name='校内百分位')),
                ('student_count', models.IntegerField(verbose_name='学生数')),
                ('avg_standard_score', models.FloatField(default=0, verbose_name='标准分均值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class', verbose_name='关联班级')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='关联考试')),
                ('school_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_insights.schoolexamfeature', verbose_name='校级特征')),
            ],
            options={
                'verbose_name': '班级考试特征',
                'verbose_name_plural': '班级考试特征管理',
            },
        ),
        migrations.CreateModel(
            name='StudentExamFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_score', models.FloatField(verbose_name='考试总分')),
                ('class_rank', models.IntegerField(verbose_name='班级排名')),
                ('school_rank', models.IntegerField(verbose_name='校内排名')),
                ('district_rank', models.IntegerField(verbose_name='区内排名')),
                ('best_subject_score', models.FloatField(verbose_name='最优学科得分')),
                ('weakest_subject_score', models.FloatField(verbose_name='最弱学科得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('best_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subject', verbose_name='最优学科')),
                ('class_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_insights.classexamfeature', verbose_name='班级特征')),
                ('district_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_insights.districtexamfeature', verbose_name='区级特征')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam', verbose_name='关联考试')),
                ('school_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu_insights.schoolexamfeature', verbose_name='校级特征')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', verbose_name='关联学生')),
                ('weakest_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subject', verbose_name='最弱学科')),
            ],
            options={
                'verbose_name': '学生考试特征',
                'verbose_name_plural': '学生考试特征管理',
            },
        ),
        migrations.CreateModel(
            name='StudentScoreFeatures',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('avg_raw_score', models.FloatField(verbose_name='原始平均分')),
                ('std_dev_score', models.FloatField(verbose_name='标准差')),
                ('max_score', models.FloatField(verbose_name='最高分')),
                ('min_score', models.FloatField(verbose_name='最低分')),
                ('score_range', models.FloatField(verbose_name='分数范围')),
                ('class_rank', models.IntegerField(verbose_name='班级排名')),
                ('grade_rank', models.IntegerField(verbose_name='年级排名')),
                ('percentile_in_grade', models.FloatField(verbose_name='年级百分位')),
                ('deviation_from_class_avg', models.FloatField(verbose_name='班级平均分差值')),
                ('z_score_avg', models.FloatField(verbose_name='Z分数均值')),
                ('county_rank', models.IntegerField(blank=True, null=True, verbose_name='区县排名')),
                ('city_rank', models.IntegerField(blank=True, null=True, verbose_name='地市排名')),
                ('county_percentile', models.FloatField(blank=True, null=True, verbose_name='区县百分位')),
                ('city_percentile', models.FloatField(blank=True, null=True, verbose_name='地市百分位')),
                ('subject_variance', models.FloatField(verbose_name='学科方差')),
                ('main_subjects_avg', models.FloatField(verbose_name='主科平均分')),
                ('minor_subjects_avg', models.FloatField(verbose_name='副科平均分')),
                ('improvement_rate', models.FloatField(blank=True, null=True, verbose_name='进步率')),
                ('consistency_index', models.FloatField(blank=True, null=True, verbose_name='稳定性指数')),
                ('underperformed_count', models.IntegerField(default=0, verbose_name='低表现次数')),
                ('weighted_performance_index', models.FloatField(verbose_name='加权表现指数')),
                ('learning_pattern_cluster', models.IntegerField(blank=True, null=True, verbose_name='学习模式聚类')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_version', models.CharField(default='1.0', max_length=10)),
                ('best_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subject', verbose_name='最优学科')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_features', to='core.student')),
                ('weakest_subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.subject', verbose_name='最弱学科')),
            ],
            options={
                'verbose_name': '学生成绩特征',
                'verbose_name_plural': '学生成绩特征管理',
            },
        ),
        migrations.AddIndex(
            model_name='schoolexamfeature',
            index=models.Index(fields=['rank'], name='edu_insight_rank_9972b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolexamfeature',
            unique_together={('exam', 'school', 'subject_id')},
        ),
        migrations.AddIndex(
            model_name='classexamfeature',
            index=models.Index(fields=['school_rank'], name='edu_insight_school__0a3941_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classexamfeature',
            unique_together={('exam', 'class_obj', 'subject_id')},
        ),
        migrations.AddIndex(
            model_name='studentexamfeature',
            index=models.Index(fields=['district_rank'], name='edu_insight_distric_1b348a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamfeature',
            index=models.Index(fields=['school_rank'], name='edu_insight_school__ff4d25_idx'),
        ),
        migrations.AddIndex(
            model_name='studentexamfeature',
            index=models.Index(fields=['class_rank'], name='edu_insight_class_r_ddb86a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentexamfeature',
            unique_together={('exam', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='studentscorefeatures',
            unique_together={('student', 'semester')},
        ),
    ]
